language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
    - composer install --dev --no-interaction
    - phpenv rehash

script:
    - ./vendor/bin/phpcs --standard=./phpcs.xml ./src
    - ./vendor/bin/phpmd ./src text ./phpmd.xml
    - ./vendor/bin/phpcpd ./src
    - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover ./build/logs/clover.xml
